### ISSUE TITLE
IMPORTANT

### ISSUE THREAD

**Issue by mugman174** [v-briese/custom-rich-presence#1]
### Is this a clone of [E-boi/custom-rpc](https://github.com/E-boi/custom-rpc)?

**Comment by v-briese** [comment]
It's not a clone, it's a port. Even if it was a clone, [E-boi/custom-rpc](https://github.com/E-boi/custom-rpc) is licensed under MIT.

**Comment by mugman174** [comment]
> It's not a clone, it's a port. Even if it was a clone, [E-boi/custom-rpc](https://github.com/E-boi/custom-rpc) is licensed under MIT.

yeah i know its MIT, but just wanted to know
